### ISSUE TITLE
need to recreate footer

### ISSUE THREAD

**Issue by seanaery** [duke-libraries/drupal-dulcet#3]
The footer regions from MadLib theme need to be added for display in Dulcet.

**Comment by mikedaul** [comment]
Perhaps this would be an opportunity to develop a universal footer (similar to the JS header)?

**Comment by seanaery** [comment]
@mikedaul Could be! I think we should keep that on the table as a nice-to-have since it'd require some considerable development, testing, etc., and take it on only if there's time between now and Jan. It'll be fairly easy to at least restore the current blocks that get rendered by the MadLib theme. There's some trickiness in there, e.g., conditionally swapping out the contact phone number.
